# Generated by Django 5.0.1 on 2024-01-25 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='social_networks/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='authors.author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
