# Generated by Django 5.0.1 on 2024-01-26 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_socialnetwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'SocialNetwork', 'verbose_name_plural': 'SocialNetworks'},
        ),
    ]
