# Generated by Django 5.0.1 on 2024-01-25 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('posts', '0002_category_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnewtork',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socails', to='authors.author'),
        ),
    ]
