# Generated by Django 5.0.1 on 2024-01-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_socialnewtork_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialNewtork',
        ),
    ]
